from pyrogram import Client, filters
from DazaiRobot import pbot as Client
import httpx


@Client.on_message(filters.command("aigen"))
async def gen_img(client, message):
    temp = await message.reply_text("**Generating, please wait...**")
    prompt = message.text.split(maxsplit=1)[1]
    data = {"prompt": prompt}
    async with httpx.AsyncClient(timeout=30) as cli:
        try:
            response = await cli.post("https://alphacoder-api-93747976af25.herokuapp.com/text2img", json=data)
            result = response.json()
            pic = result.get("output_url")[0]
            await client.send_photo(message.chat.id, photo=pic, caption=f"**Image generated by @Dazaiprobot**")
            await temp.delete()
        except Exception as e:
            await temp.edit_text(f"**An error occurred:\n**`{str(e)}`")
